[package]
name = "gromp"
version = "0.1.0"
authors = ["Andy Grover <agrover@redhat.com>"]

[dependencies]
byteorder = "0.3.10"
crc = "^0.3.1"
unix_socket = "*"
# nix = "*"

[dependencies.nix]
git = "https://github.com/carllerche/nix-rust.git"
